# Generated by Django 4.0.4 on 2022-06-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('stars', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=80)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab2_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=90, null=True)),
                ('rate', models.CharField(max_length=90, null=True)),
                ('date', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab2_1.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='message_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab2_1.message'),
        ),
        migrations.AddField(
            model_name='client',
            name='message_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab2_1.message'),
        ),
    ]
